name: hani_almutairi_logistic
description: hani almutairi logistic is a logistics company plans, implements, and controls the movement and storage of goods, services or information within a supply chain and between the points of origin and consumption.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  pdf: ^1.12.0
  dio: ^3.0.10
  http: ^0.12.1
  async: ^2.4.2
  provider: ^4.3.1
  flushbar: ^1.10.4
  clipboard: ^0.1.2+8
  flutter_html: ^1.1.1
  url_launcher: ^5.7.10
  fluttertoast: ^7.1.1
  path_provider: ^1.6.24
  flutter_phoenix: ^0.1.0
  dropdown_search: ^0.4.8
  grouped_buttons: ^1.0.4
  download_manager: ^1.0.1+2
  shared_preferences: ^0.5.8
  font_awesome_flutter: ^8.0.1
  cached_network_image: ^2.3.3
  pin_input_text_field: ^3.1.1
  # flutter_full_pdf_viewer: ^1.0.6
  # pdf_render: ^0.57.2
  # flutter_pdf_viewer: ^0.6.1
  # flutter_full_pdf_viewer: ^1.0.6
  # universal_html: ^1.2.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/logo.png
    - assets/images/dummy_profile.png
    - assets/images/header.jpg
    - assets/images/fragile_sticker.png
    - assets/lang/en.json
    - assets/lang/ar.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
